{
  'name':'Aditim Theme',
  'description': 'Aditim Enterprice Theme.',
  'version':'1.0',
  'author':'Aditim',
  'data': [
           'data/demo.xml',
           'security/aditim_security.xml',
           'security/ir.model.access.csv',
           'views/snippets.xml',
           'views/top_menu.xml',
           'views/assets.xml',
           'views/layout.xml',
           'views/website_blog_views.xml',
           'views/crm_lead_view.xml',
           'views/website_case_view.xml',
           'views/product_template_view.xml',
           'views/product_category_view.xml',
           'web/main_page.xml',
           'web/product_page.xml',
           'web/product_interior_page.xml',
           'web/contactus_interior_page.xml',
           'web/search_page.xml',
           'web/blog_aggregator.xml',
           'web/blog_inner_page.xml',
           'web/projects.xml',
           'web/projects_interior_page.xml',
           'web/aboutus_page.xml',
           'web/product_accessories_detail.xml',
           'web/product_polyamide_detail.xml',
           'web/product_seals_detail.xml',
           'web/product_thermal_detail.xml',
           'web/product_thermix_detail.xml',
  ],
  'category': 'Theme/Theme',
  'depends': ['website', 'website_sale', 'website_blog', 'crm'],
}